### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by majovec** [robske110/SignServerStats#3]
Fatal error: Declaration of robske_110\SSS\SSSAsyncTaskCaller::onRun(int $curren
tTick) must be compatible with pocketmine\scheduler\Task::onRun($currentTick) in
 phar:///root/lobby/plugins/SignServerStats_v1.0.0-InDev-beta2.phar/src/robske_1
10/SSS/SSSAsyncTaskCaller.php on line 26

**Comment by ghost** [comment]
You use PocketMine-MP?

**Comment by majovec** [comment]
GenisysPro

**Comment by ghost** [comment]
This is not compatible with GenisysPro

**Comment by robske110** [comment]
Yup, this is updated for 3.0.0-ALPHA7, which mosts spoons don't support.
You can use an old version
https://github.com/robske110/SignServerStats/releases/tag/0.9.1
Also, don't use spoons and don't support them. They really make a life of a plugin developer hard, because they always have a somewhat different API as pmmp.
